[profile.default]
solc_version = "0.8.30"
src = "src"
out = "out"
libs = ["lib"]

## Coverage requires viaIR and optimizer to avoid some codegen "stack too deep" issues.
# These settings are intentionally enabled to allow `forge coverage` to compile the codebase
# when complex functions trigger codegen stack depth problems. They can be reverted if
# you prefer the prior settings after running coverage.
viaIR = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
