name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Cache Foundry dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry/cache
            lib
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}-${{ hashFiles('**/remappings.txt') }}

      - name: Install dependencies
        run: |
          forge --version
          forge build

      - name: Run tests
        run: |
          forge test -vv
